replicaCount: 1
image:
  repository: 672262484140.dkr.ecr.us-east-1.amazonaws.com/cactustech-challenge

namespace: argocd

specs:
  service:
    name: http
    port: 3000
    protocol: TCP
    type: ClusterIP
